# Generated by Django 3.2.9 on 2021-11-13 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auth_group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='auth_user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='hospital_appointment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('appointmentDate', models.DateField()),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('doctorName', models.CharField(max_length=40)),
                ('patientName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital_department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='hospital_doctor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=40)),
                ('status', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(upload_to='hospital_doctor')),
                ('mobile', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalAPP.auth_user')),
            ],
        ),
        migrations.CreateModel(
            name='hospital_MedcineBrand',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='hospital_MedcineType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='hospital_patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('symptoms', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('admitDate', models.DateField(default=False)),
                ('profile_pic', models.ImageField(upload_to='hospital_patient')),
                ('assignedDoctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalAPP.hospital_doctor')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalAPP.auth_user')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital_PaymentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='hospital_room',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('roomNum', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='hospital_roomKind',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='zipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=90)),
                ('state', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='hospital_roombookings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('startDatetime', models.DateTimeField()),
                ('endDatetime', models.DateTimeField()),
                ('appointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalAPP.hospital_appointment')),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalAPP.hospital_room')),
            ],
        ),
        migrations.AddField(
            model_name='hospital_room',
            name='roomKindId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalAPP.hospital_roomkind'),
        ),
        migrations.CreateModel(
            name='Hospital_patientPayment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('referenceDetails', models.CharField(max_length=200)),
                ('paymentTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalAPP.hospital_paymenttype')),
            ],
        ),
        migrations.CreateModel(
            name='hospital_patientInsurance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=120)),
                ('Insurance_Number', models.CharField(max_length=120)),
                ('Insurance_Type', models.CharField(max_length=120)),
                ('ExpiryDate', models.DateField()),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalAPP.hospital_patient')),
            ],
        ),
        migrations.CreateModel(
            name='hospital_patientdischargedetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('patientName', models.CharField(max_length=40)),
                ('assignedDoctorName', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('symptoms', models.CharField(max_length=100)),
                ('admitDate', models.DateField()),
                ('releaseDate', models.DateField()),
                ('daySpent', models.IntegerField(default=0)),
                ('roomCharge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('medicineCost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('doctorFee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('OtherCharge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalAPP.hospital_patient')),
            ],
        ),
        migrations.CreateModel(
            name='hospital_Medcine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('BrandId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalAPP.hospital_medcinebrand')),
                ('typeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalAPP.hospital_medcinetype')),
            ],
        ),
        migrations.CreateModel(
            name='hospital_doctor_departments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalAPP.hospital_department')),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalAPP.hospital_doctor')),
            ],
        ),
        migrations.CreateModel(
            name='hospital_dischargeMedication',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('medcineName', models.CharField(max_length=150)),
                ('dose', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('medcineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalAPP.hospital_medcine')),
            ],
        ),
        migrations.AddField(
            model_name='hospital_appointment',
            name='doctorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalAPP.hospital_doctor'),
        ),
        migrations.AddField(
            model_name='hospital_appointment',
            name='patientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalAPP.hospital_patient'),
        ),
        migrations.CreateModel(
            name='auth_user_groups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalAPP.auth_group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalAPP.auth_user')),
            ],
        ),
    ]
