# Generated by Django 3.0 on 2021-11-17 00:22

from django.db import migrations, models
import django.utils.translation


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_appointment',
            name='status',
            field=models.CharField(default=django.utils.translation.activate, max_length=30),
        ),
    ]
